assets/entrypoint
assets/pod-director-client.yaml
assets/pod-director-server.yaml
directord/main.py
directord/mixin.py
directord/server.py
directord/utils.py
docs/containerization.md
docs/testing.md
orchestrations/scale-test-setup.yaml
orchestrations/scale-test.yaml
setup.py
tools/directord-inventory-catalog.yaml

This change implements a performance and scale test orchestration example.
Additionally changes have been made to the server code to further improve scale operations.
Using the test setup with 408 nodes and the `ssh-keygen-distribute.yaml` orchestration example we saw an execution time of **2549.27**. After the scale and performance improvements we the time was reduced to **516.51**.
Quality of life changes have been added to ensure a better operator experience.

Performance scale

---

directord/main.py
directord/mixin.py
directord/server.py
directord/tests/test_user.py
directord/user.py

Operators can now fingerprint and enumerate an orchestration
allowing them to understand what will be executed and when
while also providing a set of SHA1 IDs that could be used to
restrict a given orchestration across an environment.

Add fingerprint functionality

---

directord/main.py
directord/meta.py
directord/mixin.py
directord/tests/__init__.py
directord/tests/test_mixin.py
directord/tests/test_utils.py
directord/utils.py
setup.py
tools/prod-setup.sh

this change updates our ssh implementation to use libssh instead of paramiko, which allows us to meet FIPs requirements within the bootstrap codepath.

Libssh > Paramiko

---

directord/__init__.py

If you attempt to connect to the directord socket as a user that cannot
write to the socket, a permission exception is thrown but no details
indicating what file are provided to the user. This catches the
Permission error and prints out the socket path for use in
troubleshooting.

Add logging around permission errors for socket

---

contrib/container-build/directord.spec
directord/components/builtin_transfer.py
directord/components/builtin_workdir.py
directord/main.py
directord/server.py
directord/templates/directord-client.service.j2
directord/templates/directord-server.service.j2
directord/tests/__init__.py
directord/tests/test_main.py
directord/tests/test_server.py
tools/directord-prod-bootstrap-catalog.yaml

When deploying directord via rpm the system should have, and use, a
group to manage the process. this change implements the directord group
within the RPM spec, and ensures that we can define the used group when
rendering / deploying systemd service units via the directord CLI
utilities.

Add group abilities

---

directord/tests/test_user.py
directord/user.py

The server side client maybe used in higher level applications which
could create a conflict in processing which violates the use of signals.
This change removes the signal timeout client side which should resolve
any signal related issues.
Fixes https://github.com/cloudnull/directord/issues/99

Remove signal timeout in client

---

directord/components/builtin_dnf.py
directord/tests/test_components.py
docs/components.md

Adds a DNF builtin for use with managing packages on the target node.
Signed-off-by: Alex Schultz <aschultz@next-development.com>

Create dnf builtin

---

directord/components/builtin_dnf.py
directord/tests/test_components.py

Using the systemcache seems to be inconsistent. Let's skip this for now.

Drop -C from dnf installs

---

components/container_config_data.py
components/echo.py
components/pod.py
components/secontext.py
directord/client.py
directord/components/__init__.py
directord/components/builtin_cache.py
directord/components/builtin_cacheevict.py
directord/components/builtin_cachefile.py
directord/components/builtin_dnf.py
directord/components/builtin_query.py
directord/components/builtin_run.py
directord/components/builtin_transfer.py
directord/components/builtin_workdir.py
directord/tests/test_client.py
directord/tests/test_components.py
docs/components.md

This change removes all of the connection interactions from the
components and puts them back into the client module. This ensures
better separation between our components and the execution, simplifies
interactions, and will allow us to further pursue async client side
operations.

Remove conn from the components

---

.github/workflows/pull-request.yml
directord/client.py
directord/components/builtin_query.py
directord/meta.py
directord/mixin.py
directord/server.py
directord/tests/test_client.py
directord/tests/test_mixin.py
directord/tests/test_server.py
docs/components.md
orchestrations/functional-tests-async-race.yaml

When running call-back jobs from a given parent, the call-back task
should have the ability to execute in-front of any other blocking tasks.
This change provides the ability to bypass the queues and run in a new
daemonic thread.

add parent async bypass

---

.github/workflows/push.yml

This change will allow merges to push a pre-release build to PYPI and provide that build as an artifact here.

add pre-release pypi workflow

---

directord/main.py

Allow the config file to be empty instead of throwing an error.

Handle empty config

---

components/query_wait.py
directord/client.py
directord/components/__init__.py
directord/components/builtin_query.py
directord/server.py

Call back jobs is now an array of jobs
This gives component developers the ability to run multiple jobs as a call back as needed while also ensuring the order of execution is correct by blocking on the last job within the array.

Use comment parent ids when running call back jobs

---

components/job_wait.py
directord/components/builtin_arg.py
directord/components/builtin_query.py
docs/components.md

New component JOB_WAIT has been added. This will allow an orchestration
to block on a particular job SHA to be in a completed state.

Ensure query always runs follow-on tasks

---

directord/components/builtin_dnf.py

While dnf has locking, it's not exactly async friendly so let's add a
lock requirement to the DNF component.

Add lock to DNF

---

directord/components/builtin_arg.py
directord/components/builtin_cacheevict.py
directord/components/builtin_cachefile.py
directord/components/builtin_copy.py
directord/components/builtin_dnf.py
directord/components/builtin_query.py
directord/components/builtin_run.py
directord/components/builtin_workdir.py

To help determine job/cache issues, it would be beneficial to have a
debug entry at the start of the component client() call.

Add debug for client call

---

directord/components/__init__.py
directord/tests/__init__.py

There can be a race condition when updating a value because pop would
remove it from the cache for a period of time. Switching to get will
prevent the value from completely disappearing if others attempt to
fetch it while it's being updated. There is still a race if two tasks
are running in parallel that expect a value to be provided by one of the
tasks for the other.

Fix set_cache to use get and not pop

---

.github/workflows/pull-request.yml
directord/components/builtin_cacheevict.py
directord/components/builtin_run.py
directord/tests/test_components.py

When executing RUN with stdout args we should set the cache using the
ARG component, which provides a thread safe interface. This change
removes the RUN commands direct cache access and replaces it with a
callback.

use callback task to set stdout-args

---

directord/components/builtin_run.py

When running RUN with --stdout-arg we need to to ensure that
the ARG is scoped to the correct node. This change uses the
driver identity to ensure the callback ARG is scoped accordingly.
Fixes: https://github.com/cloudnull/directord/issues/164

ensure that the stdout-arg target is defined

---

directord/client.py

this will ensure we're only allowing call back tasks to block until failed or success status. 
tasks can have a null status while pending, the call back task was releasing the block too early in some cases. this will ensure we're blocking correctly.

ensure we're only blocking for tasks that have ended or failed

---

directord/client.py
directord/components/__init__.py
directord/tests/test_components.py
docs/components.md

Operators can now force a task to run with a lock, which will allow
users to define blocking operations.

add force-lock option

---

directord/client.py
directord/server.py
directord/tests/test_server.py

This change sets the time block to 0.01 when work is present, which is a
reasonable poller duration. The old blocks were used to capture work and
simualte a busy environment. While the old blocks we're by no means
slow, this change will imporve execution by an order of magnatude.

remove artificial time blocks

---

directord/client.py
directord/server.py
directord/tests/test_server.py
directord/utils.py
tox.ini

This change will ensure that parent pruning is not overzealous and
allows a given parent process time to continue accpeting work.
* Also moves the bypass queue into a single queue with many threads
instead of many queues with a single thread. This was a regression.

add timestamps to parent pruning

---

directord/client.py
directord/components/builtin_query.py
directord/components/builtin_run.py
directord/main.py
directord/mixin.py
directord/server.py
directord/tests/test_main.py
directord/tests/test_mixin.py

Async tasks will now use the parent ID within the queue name. This is
done so that operators can now see when a queue is executing and when it
is pruned.
Allow query to run without waiting for the cache to be populated with
the queried value.
All exec tasks can now be forced into an async mode.

Server return and async tracing

---

directord/tests/__init__.py

Without this patch, running a subset of unit tests that inherit from
directord.tests.TestDriverBase fail like so:
$ .tox/coverage/bin/python -m unittest directord.tests.test_user.TestManager
...
TypeError: __name__ must be set to a string object
The zmq.Driver class is correctly unmocked for some reason.

Save a reference to zmq Driver, and restore it for each unit test

---

.github/workflows/pull-request.yml
components/job_wait.py
components/query_wait.py
directord/bootstrap.py
directord/client.py
directord/components/__init__.py
directord/components/builtin_arg.py
directord/components/builtin_copy.py
directord/datastores/disc.py
directord/server.py
directord/tests/test_client.py
directord/tests/test_server.py
directord/utils.py

This change reworks our health check process which ensures we're running
a very lean application with all the required functionality.
* The health check thread was remove.
* The client q processor now uses an ordered dict to manage the threads which ensures consistent execution.
* cache adds will now automatically retry and return the state of the cache add attempt which will help ensure we're recording the job execution appropriately.
* Client thread spawning is now totally dynamic. At idle, there's now only one PID.

Healthcheck isolation

---

directord/client.py
directord/drivers/__init__.py
directord/interface.py
directord/server.py
docs/service-setup.md

Now that the thread pool is dynamic and the socket communication process
has been simplified, we can remove the heartbeat socket all together and
making the application even more simple and lighter. 
* Heartbeats are still used, but they're processed using control objects on the
on job socket. In a future release we're look to reuse the heartbeat socket
or remove the code path all together.

Remove the use of the server side heartbeat socket

---

components/query_wait.py
directord/client.py

Job callbacks could contain many jobs, because we know that the jobs
will be run serially, this change instructs the client to only wait on
the last job provided.

when waiting on callbacks, just block on the last one

---

tox.ini

Allows for running individual unit tests with tox like so:
tox -e coverage -- directord.tests.test_drivers_zmq

Add {posargs} to tox coverage command

---

directord/main.py

The CLI arguments should override what is in the config file. This
change adds a step to reparse the CLI args (sys.argv) after options are
read from the config file. When options are common between the CLI and
the config file, the CLI will take precedence.

Make CLI args override config file

---

directord/drivers/__init__.py
directord/drivers/messaging.py
directord/drivers/zmq.py
directord/main.py
directord/server.py
directord/tests/test_drivers_messaging.py

While it all hosts should have unique names, it is possible for two
machines to be misconfigured, resulting in multiple machines with the
same host name. To ensure we're able to address machine correctly and
that the server is maintaining a correct inventory, the heartbeat
process will now collect the machine id and use that unique id for
fencing. Should multiple machines with the same hostname but different
machine ids try to join the cluster an error will be raised and the new
node will not be permitted to join. A log entry will be generated on
how to fix the issue.

add hostname fencing

---

directord/client.py
directord/drivers/__init__.py
directord/drivers/messaging.py
directord/drivers/zmq.py
directord/tests/test_client.py

driver_run (renamed from _run) needs to start in its own process outside
of the Driver __init__. Otherwise the interface class (Server) is not
initialized.

Add driver_run in it's own process

---

directord/client.py
directord/drivers/messaging.py
directord/server.py

Fixes the messaging driver heartbeat by setting up the rpc target as the
machine_id, but still uses the identity (hostname) to identify the
worker in server.py.
Also adds the accidentally removed heartbeat method in messaging.py.

Fix messaging heartbeat

---

components/job_wait.py
directord/bootstrap.py
directord/client.py
directord/drivers/__init__.py
directord/drivers/messaging.py
directord/drivers/zmq.py
directord/server.py
directord/tests/__init__.py
directord/tests/test_drivers_messaging.py
directord/user.py
test-requirements.txt
tox.ini

add flake8 docstring tests
Correct stacktrace when no messaging driver server object is None
Ensure that we're always using lazy logging
Move internal messaging driver methods to private methods
Add missing messaging job test
Remove type objects, we're not using them and they cause incompatibility
with older python versions

D102 updates

---

directord/drivers/messaging.py
directord/tests/test_drivers_messaging.py

This change updates the messaging driver so that it contains all of the
required public methods from the driver abstract. This should help
solidify everything we need to do to get the messaging driver prod-ready.
Non-specific driver methods that are not intended to be public have been
prefixed with an underline.

add missing abstract methods from messaging

---

.github/workflows/push.yml
components/job_wait.py
directord/client.py
directord/drivers/__init__.py
directord/drivers/messaging.py
directord/drivers/zmq.py
directord/main.py
directord/server.py
directord/tests/__init__.py
directord/tests/test_drivers_messaging.py

The credit loop will allow the server and client to run multiple
processes with realtime updates, without blocking or locking any
particular messaging function for prolonged periods of time.
* The ZMQ driver has also had the unlimited hwm setting remove
now that the credit system has been implemented.

Add credit loop to pollers

---

directord/mixin.py
docs/orchestrations.md

This change will allow operators to override the targets for a given set
of tasks. The new `assign` key provides the ability to define a list of
targets which may be outside the scope of the current orchestration.
The `assign` option is a list of all intended targets and is validate
upon orchestration ingest.
Closes #269

Add option to allow orchestrations to override targets

---

SECURITY.md
contrib/container-build/directord.spec
docs/analysis.md
docs/components.md
docs/installation.md
tools/prod-setup.sh

Now directod is maintained under the 'directod' organization. This
change updates the repositories mentioned in documentation as well as
the ones used in scripts.
Note that container image is still maintained under the original
organization.

Migrate to directord organization

---

components/container_config_data.py
contrib/container-build/Containerfile
contrib/container-build/directord.spec
directord/client.py
directord/components/__init__.py
directord/components/builtin_arg.py
directord/components/builtin_cachefile.py
directord/datastores/disc.py
directord/server.py
directord/tests/__init__.py
directord/tests/test_client.py
directord/tests/test_components.py
directord/tests/test_datastore_disc.py
directord/tests/test_drivers_zmq.py
directord/tests/test_init.py
directord/tests/test_server.py
directord/tests/test_user.py
directord/tests/test_utils.py
directord/user.py
directord/utils.py
setup.py
tools/prod-setup.sh

This change removes diskcache as a dependency from Directord. While the
diskcache lib is well maintained and works well for our usecase, the
library is an additional dependency which operators need not maintain or
worry about. This change converts our caching mechanism to a native
python shelve.

Remove the diskcache dep

---

directord/drivers/__init__.py
directord/interface.py
directord/main.py
directord/tests/__init__.py
directord/tests/test_main.py

This change allows operators to define the machine id. While the machine
id should be auto generated, when running in containerized infra, the ID
is passed through to the container, so to be able to run multiple
directord containers on a single host, we need the ability to define a
unique id.

Add option to allow operators to set the machine id

---

components/container_image.py
components/pod.py
directord/components/lib/podman.py
directord/tests/test_components.py

It was impossible to set TLS verify to False, use `--no-tlsverify` option for that.
Use unified var name `tlsverify` through podman modules.

Fix TLS verify for all podman code

---

tools/directord-dev-bootstrap-messaging-catalog.yaml

Connect to each client to get the hostname, not the node running the
directord bootstrap. Previously, this only worked when it was an all in
one node running the client and server. This change makes the messaging
bootstrap work across multiple client nodes.

Connect to client to get hostname

---

directord/client.py
directord/drivers/__init__.py
directord/drivers/messaging.py
directord/drivers/zmq.py
directord/meta.py
directord/server.py
directord/tests/__init__.py
directord/tests/test_client.py
directord/tests/test_server.py

Server side job handling was all done within a consistent loop, this
change adds a quick handling check when sending so that the server is
always processing data, and never in an idle state when work is needed
to be done.
The credit process is no longer needed and removing it will improve
performance by about 5%. This change removes the credit functions
from the core client and server and improves some logging.
Meta rev to 0.11.2
JOB ACK was removed. The job ack control no longer has any purpose given
the use of the processing control. The job ack was an old interaction
which was kept for legacy purposes. Removing this interaction improves
server throughput by removing processing overhead.

Job interaction improvements

---

directord/bootstrap.py

The server stanza shouldn't require job entries as server data could be
used to bootstrap client only.

fix bootstrap server targets

---

tools/directord-dev-bootstrap-zmq-no-server.yaml

Sometimes need to provision only clients when server is already up.
Provide the dev orchestration for this case.

Add orch file for provisioning clients only

---

directord/components/builtin_dnf.py
directord/components/builtin_run.py
directord/components/builtin_service.py
directord/components/lib/__init__.py
directord/tests/test_mixin.py

Components can now use retries where they make sense. The new component
retry decorator will make use of the outcome and retry when instructed
to do so.
Components like DNF and SERVICE will retry 3 times by default, while RUN
will run once, but allow operators to specify a retry when desired.

add retry decorator to components

---

directord/datastores/redis.py
directord/drivers/__init__.py
directord/server.py

The machine id check was checking for duplicate hosts with unique
machine IDs. This change adds a check for duplicate machine IDs so that
we're only ever operating with unique devices.

update machine checking and messaging workers

---

directord/components/lib/__init__.py

The timeout function was removed because it was not compatible with
threads. This change reimplements the timeout function on directord
client interactions using an async coroutine.

Add coroutine timeout decorator

---

directord/__init__.py
directord/client.py
directord/drivers/__init__.py
directord/drivers/zmq.py
directord/server.py
directord/tests/test_drivers_messaging.py
directord/tests/test_drivers_zmq.py
directord/tests/test_init.py
directord/utils.py

Locks can not be mixed and matched, this change ensures that the driver
code, which is responcible for the process execution is selecting the
correct lock types.

ensure that drivers use process based locks

---

directord/client.py
directord/components/builtin_arg.py
directord/components/builtin_copy.py
directord/utils.py

Some components are aliases, which are there for ease of use, however,
these aliaes need to have unique locks.

Ensure components have unique locks

---

directord/drivers/grpcd.py
directord/drivers/messaging.py

Needs to be wrapped in a bool so the env value is properly interpreted.

Fix disable compression default

---

setup.py

The entrypoint for drivers is no longer needed as the entrypoint loading
code was removed in cd59fcd6ccdfee4dff44ffde4a4154a02ff6b0d3.

Remove messaging drivers entrypoint

---

directord/drivers/grpcd.py
tools/directord-dev-bootstrap-grpc-ssl.yaml
tools/scripts/grpcd/getcert.sh
tools/scripts/grpcd/grpcd-ssl-setup.sh
tools/scripts/grpcd/set-ca.sh

The grpc client and server support ssl and ssl based authentication.
This change wires up the grpc ssl flag and builds the credentials as
needed.

Wire up ssl support for grpc

---

directord/__init__.py
directord/client.py
directord/drivers/__init__.py
directord/server.py
directord/tests/__init__.py
directord/tests/test_client.py
directord/tests/test_init.py
directord/tests/test_server.py

This change implements a handler for thread exceptions which will
reraise on join allowing the application to shutdown gracefully when
exceptions are encountered.

Create thread exception class and terminate events

---

directord/templates/directord-server.service.j2

For grpc with ssl, this is necessary as the number of sockets is more
than the default limits because multiple connections are created by the
clients.

Increase file limits for the server

---

directord/drivers/grpcd.py

The client can be shared between threads so making it a single instance
that is used between job threads prevents excessive amount of sockets
being opened when ssl is enabled.

Only create a single client instance

---

.github/workflows/pull-request-functional.yml
directord/client.py
directord/drivers/__init__.py
directord/drivers/zmq.py
directord/main.py
directord/tests/__init__.py
directord/tests/test_components.py
directord/tests/test_datastore_disc.py
directord/tests/test_main.py
directord/utils.py
docs/overview.md

With the durable queue option, clients can recover tasks and
other operations should the client ever crash. This option has been
added to the application main as both an environment variable and CLI
switch.

Add durable queue type option for clients

---

directord/client.py

the client side execution handler will now try / except and in the event
of an error it will return back information to the user showing what
failed and where.

Add exception handling to client execution

---

directord/drivers/grpcd.py

Since we switched to a single client shared between all threads, we
don't want to close the client with the driver's job_close function.
Fixes #338

Skip client close on job close

---

setup.py

Need to make sure to grab the grpcd setup scripts for installation.

Add grpc scripts to packaging

---

directord/drivers/grpcd.py
directord/tests/__init__.py
directord/tests/test_drivers_grpcd.py

Coverage the grpc driver with some unit tests. This also fixes a few
issues found during testing:
* Message and Job queue objects were being shared
* SSL auth requirement wasn't honored
* Fix queue stats call

Cover grpc driver with tests

---

directord/components/builtin_query.py

When query is not string, but different datatype, it can't be sent
as is, causing socker_send failure.
Send not the query value, but only key in query information part.

Fix query information part

---

directord/components/builtin_service.py
directord/tests/test_components.py
docs/syntax.md

We may want to reload a service rather than start/restart/stop.  This
change adds --reloaded to the service component to be able to trigger a
reload.  This change also fixes the logic around state/running.

Add --reloaded to service component

---

directord/__init__.py
directord/client.py
directord/server.py

This change will allow directord to attempt a graceful shutdown of the
application. Because signals can not be used in multi-threading, all
of the signal processing is handled pre-fork|thread. The server|client
classes then use the driver event handler to begin a system shutdown
when a signal is encountered.

use pre-fork signals to allow exit

---

directord/client.py
directord/drivers/__init__.py
directord/drivers/dummy.py
directord/drivers/zmq.py
directord/server.py
directord/tests/__init__.py
directord/tests/test_bootstrap.py
directord/tests/test_client.py
directord/tests/test_components.py
directord/tests/test_datastore_disc.py
directord/tests/test_datastore_internal.py
directord/tests/test_datastore_redis.py
directord/tests/test_drivers_grpcd.py
directord/tests/test_drivers_messaging.py
directord/tests/test_drivers_zmq.py
directord/tests/test_init.py
directord/tests/test_logger.py
directord/tests/test_main.py
directord/tests/test_mixin.py
directord/tests/test_server.py
directord/tests/test_user.py
directord/tests/test_utils.py

This change cleans up our unit tests so that we're not seeing all the
socket output from runs.
Like so...
```
Object allocated at (most recent call last):
File "/home/cloudnull/projects/directord/directord/drivers/zmq.py", lineno 146
self._context = zmq.Context()
```
This will help us better understand out test output and allow new folks
to better grok issues are they onboard.
A dummy driver was added to allow for easier testing across related
classes.

Cleanup tests to remove the crazy output

---

contrib/container-build/Containerfile
contrib/container-build/builder.sh
contrib/container-build/directord.spec
directord/datastores/disc.py
directord/tests/test_datastore_disc.py
directord/utils.py
setup.py
tools/prod-setup.sh

IODict is a library developed under the directord organization and
serves as a replacement for the current Cache class. While the Cache
class and IODict are similar, IODict implements the whole python dict
API, and provides 100% test coverage.
IODict is a new dependency, from within the Directord organization. This
will require additional packaging efforts, but will provide a cleaner
code base within directord and serve as a starting point to close the
durable queue efforts related to issue #343.

Replace the cache class with iodict

---

directord/client.py
directord/components/__init__.py
directord/components/builtin_cacheevict.py
directord/datastores/__init__.py
directord/datastores/disc.py
directord/datastores/memory.py
directord/datastores/redis.py
directord/drivers/__init__.py
directord/drivers/zmq.py
directord/server.py
directord/tests/__init__.py
directord/tests/test_client.py
directord/tests/test_components.py
directord/tests/test_datastore_internal.py
directord/tests/test_datastore_redis.py
directord/tests/test_drivers_messaging.py
directord/tests/test_drivers_zmq.py
directord/tests/test_init.py
directord/tests/test_user.py
directord/user.py
directord/utils.py

Replace volatile client and server queue types
The volatile queue types for both client and server have replaced with a
durable queue. The durable queue class is now part of utils, and builds
upon our existing cache class. When Directord is shutdown, items in
queue will now be flushed to disk and restored as needed. This works on
both the server and client giving directord durability across shutdowns.
* When a shutdown is started, directord will flush all pending operations
to disk, finish inflight operations, and cleanly stop. Upon restart,
directord will look for on-disk queues and continue working on anything
discovered.
Closes #343

DurableQueue

---

.github/workflows/pull-request-functional.yml
README.md
directord/datastores/__init__.py
directord/datastores/disc.py
directord/datastores/redis.py
directord/drivers/messaging.py
directord/interface.py
directord/server.py
directord/tests/test_server.py
docs/syntax.md

This change moves the worker items from a hash object to a class, which
has dynamic properties to assist Directord in known the state of
workers. This will help us further enhance the worker experience and
make intellegent decisions about cluster activities when required.

Move the worker items into a object

---

directord/datastores/__init__.py
directord/datastores/disc.py
directord/datastores/redis.py
directord/interface.py
directord/server.py
directord/tests/test_server.py

When a node is active, work will be sent, if a node is inactive no work
will be sent to the node and that node will not be removed when expired.
Upon the nodes next healthcheck, the node will be reset as active and
all queued tasks will be sent at that time.
Related-Bug: #343

Add server side logic to mark nodes active

---

contrib/container-build/builder.sh
contrib/container-build/directord.spec
directord/client.py
directord/datastores/disc.py
directord/drivers/__init__.py
directord/drivers/zmq.py
directord/iodict.py
directord/tests/__init__.py
directord/tests/test_components.py
directord/tests/test_iodict.py
directord/tests/test_user.py
directord/user.py
directord/utils.py
setup.py
tools/prod-setup.sh

iodict was a stand-alone dep, this change pulls that developed dep back
into the core code base so that we're not having to deal with and manage
separate packages.

reintegrate iodict

---

directord/__init__.py
directord/client.py
directord/interface.py
directord/server.py

Signals can not be part of the client interface, otherwise they'll
create a conflict should the client class use multiprocessing.
Closes: #363

move signals to the process interface

---

directord/server.py

This is causing query tasks to error out early because the query may
take a while on some nodes to start executing.  This likely needs to be
revisited to better handle query timeouts.

Drop server side query timeout

---

directord/bootstrap.py
directord/main.py
directord/tests/__init__.py
directord/tests/test_bootstrap.py

Instead of using an argparse parser as the interface to the Bootstrap
class, use individual arguments instead. This makes the interface more
generically consumable from other tools (tripleoclient).

Use individual args for bootstrap interface

---

tools/directord-rpm-bootstrap-zmq.yaml

sudo is required in these RUN jobs as the ssh user may not be root.

Use sudo in rpm and config bootstrap

---

tools/directord-manage-bootstrap.yaml
tools/directord-unmanage-bootstrap.yaml

The manage and unmanage bootstraps are used to stop and start directord
services across the cluster.

Add bootstraps to manage/unmanage the cluster

---

docs/drivers.md

Need to fix some working around the CA and fix up some ordering.
Additionally drop the docs/Gemfile.lock as it's in .gitignore so it needs
to not be in the repo.

Minor updates to grpc ssl docs

---

.github/workflows/pull-request-facter.yml
.github/workflows/pull-request-functional.yml
.github/workflows/pull-request-podman.yml
Containerfile
directord/components/builtin_service.py
directord/drivers/dummy.py
directord/drivers/grpcd.py
directord/drivers/messaging.py
directord/drivers/zeromq.py
directord/drivers/zmq.py
directord/main.py
directord/tests/__init__.py
directord/tests/test_drivers_zmq.py
directord/tests/test_main.py
docs/analysis.md
docs/drivers.md
setup.py
tools/ansible-bootstrap-playbook.yaml
tools/dev-setup.sh
tools/directord-config-bootstrap-zmq.yaml
tools/directord-dev-bootstrap-zmq-encryption-catalog.yaml
tools/directord-dev-bootstrap-zmq-no-server.yaml
tools/directord-dev-bootstrap-zmq.yaml
tools/directord-prod-bootstrap-zmq.yaml
tools/directord-restart-catalog.yaml
tools/prod-setup.sh

This change will allow each driver to run in isolation and ensure that
the options provided by the driver are only present in CLI interactions
when the driver would be functional. Non-functional drivers will be
omitted in the help output. This is a UX improvement, as well as a
packaging one.

Allow drivers to run in isolation

---

directord/drivers/grpcd.py
setup.py

This change attempts to use grpc-tools dynamic code generation but will
fall back to our version we generated with 1.26.0 if we're running with
an older version of the tools.

Add support for dynamic grpc code gen

---

README.md
tools/dev-setup.sh

Server and Clients require cmake to install ssh-python during the bootstrap process.

Cmake dependency

---

tools/dev-setup.sh

While tripleo-repos doesn't support CentOS 9, add repos manually from trunk.rdoproject.org

Add repos for CentOS 9

---

directord/drivers/grpcd.py

If grpcio-tools isn't available, you get an AttributeError instead of an
NotImplementedError.

Handle if grpcio-tools isn't installed

---

directord/client.py

Return info as string instead of traceback object

---

directord/constants.py
directord/main.py
directord/server.py
directord/tests/test_server.py
docs/syntax.md

Adds support for the "last" special identifier with the --job-info
commands, which can be used to show the last (most recent) execution.

Support "--job-info last"

---

contrib/container-build/Containerfile
contrib/rpm/directord.spec
tools/dev-setup.sh

It's no longer necessary to build python3-ssh-python as it's now
packaged in RDO. It's also not a BuildRequires.

Remove python3-ssh-python build and update packaging
