directord/directord

.github/workflows/run-unit-test.yml, director/__init__.py, director/client.py, director/main.py, director/server.py, director/tests/__init__.py, director/tests/test_init.py, director/tests/test_utils.py, director/ui.py, director/user.py, director/utils.py
Adds a github action to run unit tests on a PR
=> Add some unit tests

.github/workflows/docker-build.yml, .github/workflows/run-unit-test.yml
=> add container build test

.github/workflows/run-unit-test.yml
=> stub out more test files and tweak flake8

director/user.py
SyntaxError: EOL while scanning string literal
=> Fix SyntaxError

directord/manager.py, directord/tests/__init__.py, directord/tests/test_manager.py, directord/tests/test_utils.py, directord/user.py
Implements tests for the manager module
=> Manager tests

assets/pod-director-client.yaml, assets/pod-director-server.yaml, directord/__init__.py, directord/client.py, directord/server.py, directord/tests/__init__.py, directord/tests/test_user.py, directord/user.py, docs/installation.md, docs/orchestrations.md, docs/syntax.md, docs/testing.md, orchestrations/README.md, orchestrations/files/ghost-systemd.service, orchestrations/functional-tests.yaml, tools/ansible-bootstap-playbook.yaml
Adds a full set of unit tests for the **User** module.
=> User tests

.github/workflows/auto-blacken.yml, .github/workflows/docker-build.yml, .github/workflows/run-unit-test.yml, directord/__init__.py, directord/client.py, directord/main.py, directord/manager.py, directord/mixin.py, directord/server.py, directord/tests/__init__.py, directord/tests/test_client.py, directord/tests/test_init.py, directord/tests/test_main.py, directord/tests/test_manager.py, directord/tests/test_mixin.py, directord/tests/test_server.py, directord/tests/test_ui.py, directord/tests/test_user.py, directord/tests/test_utils.py, directord/ui.py, directord/user.py, directord/utils.py
=> update job names and force greater code quality requirements

directord/mixin.py, directord/server.py, directord/tests/test_user.py, directord/user.py
Updates to improve CLI experience after feedback
Add more polling test cases.
=> improve cli info

.github/workflows/release.yml
=> add tweet action on release

.github/workflows/release.yml
=> tweek tweet message

.github/workflows/release.yml
=> add release info to tweet

.coveragerc, .github/workflows/run-unit-test.yml, setup.py
=> Add coverage report to tests

docs/syntax.md
=> add lines to syntax

.github/workflows/release.yml
=> add named tag to stable container

docs/syntax.md
=> add bullets

.github/workflows/release.yml
=> fix tweet to allow it to work with complex messages

.github/workflows/release.yml
=> remove extra elipsis

docs/components.md
=> add additional shell examples

.github/workflows/run-functional.yml, components/echo.py, directord/__init__.py, directord/client.py, directord/components/__init__.py, directord/components/builtin_cache.py, directord/components/builtin_cacheevict.py, directord/components/builtin_cachefile.py, directord/components/builtin_pod.py, directord/components/builtin_query.py, directord/components/builtin_run.py, directord/components/builtin_transfer.py, directord/components/builtin_workdir.py, directord/tests/test_components.py, directord/utils.py, docs/components.md, orchestrations/functional-tests.yaml
=> add more docs and updated component logic

.github/workflows/run-unit-test.yml, components/container_config_data.py, directord/components/__init__.py, directord/components/builtin_run.py, directord/tests/test_components.py, directord/tests/test_utils.py, directord/utils.py, docs/components.md
Adds a new blerb about converting components to Directord and adds
a new example component showing how easy it is to convert components.
=> Add additional component docs and enhancements

tools/dev-setup.sh, tools/directord-dev-bootstrap-catalog.yaml
=> remove wheels from dev script

directord/meta.py, tools/dev-setup.sh
=> update dev script

docs/overview.md
=> add a blurb about datastores

README.md, docs/index.md
=> add readme chat

docs/overview.md
=> datastore wording update

README.md, docs/index.md
=> move things around - tag libra chat

.github/workflows/pull-request-closed.yml, .github/workflows/push.yml
=> Move push notification to pr-closed

.github/workflows/pull-request-closed.yml
=> more info on push

.github/workflows/pull-request-closed.yml
=> more info on push again

.github/workflows/issue.yml
=> add an issue workflow to notify chat when an issue is opened/closed

.github/workflows/issue.yml
=> add reopen and deleted to issue action

directord/components/__init__.py
Fix the case when return_codes is an integer.
=> Return codes fix

tools/prod-setup.sh
this patch adds a sudo check to ensure privileges are sufficient prior
to run
=> add check for auth prior to script run

README.md
Adding a simple hello world in text to reduce the barrier to adoption
=> Adding a hello world section to the README

contrib/container-build/builder.sh
=> add another package

contrib/container-build/builder.sh
=> add another package (#81)

.github/workflows/push.yml, .github/workflows/release.yml, contrib/container-build/Containerfile, contrib/container-build/builder.sh, contrib/directord.spec
=> rpm tweaks

.github/workflows/push.yml, contrib/directord.spec
=> add recommends

.github/workflows/pull-request.yml, .github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/test-rpms.yml, contrib/container-build/Containerfile, contrib/container-build/builder.sh, contrib/container-build/directord.spec, contrib/rpm-build.sh
=> move test rpm workflows

components/secontext.py, docs/components.md
This implements a new component to manage selinux context.
=> Add secontext component

.github/workflows/pull-request.yml, .github/workflows/release.yml, tools/directord-prod-bootstrap-catalog.yaml, tools/prod-setup.sh
prod setup script will now install from RPM when running on cent/rhel/fedora.
=> Move prod setup script to use new RPMs

directord/utils.py
The ssh connection process will now use an explict key, or try to
connect to the ssh-agent. In the event that the ssh-agent fails, the
process will try to use the implicit key.
Fixes https://github.com/cloudnull/directord/issues/91
=> updates the SSH process

tools/dev-setup.sh
=> add devel setup for dev script

directord/templates/directord-client.service.j2, directord/templates/directord-server.service.j2
=> add socket group to the unit file

tools/directord-dev-bootstrap-catalog.yaml
=> add debug in dev mode

directord/components/builtin_cache.py, orchestrations/files/test-blueprint.yaml.j2, orchestrations/functional-tests.yaml
This change implements complex ARG handling allowing AST to parse user
input and store the value.
Fixes https://github.com/cloudnull/directord/issues/86
=> Add complex arg handling

docs/components.md
Fixes https://github.com/cloudnull/directord/issues/87
=> add blurb for cachefile usage

directord/user.py
=> re-add timeout wait option

directord/components/__init__.py, directord/tests/__init__.py, directord/tests/test_components.py, directord/tests/test_user.py, directord/tests/test_utils.py, directord/user.py, directord/utils.py, docs/library.md
Update the library usage information on states
provide True state when skipping jobs
provide an extend option when loading a cache file.
=> Update docs and ensure cache consistency

.github/workflows/pull-request.yml, directord/meta.py, directord/mixin.py, test-requirements.txt, tools/directord-prod-bootstrap-catalog.yaml, tools/prod-setup.sh, tox.ini
implements tox and converts the workflows to use it.
Adds test tools for easier development.
improves install scripts.
=> Tools improvement

directord/components/builtin_dnf.py, docs/components.md
It should be mutually not mutual
Signed-off-by: Alex Schultz <aschultz@next-development.com>
=> Fix mutually exclusive name

directord/client.py
=> Use bytes for error message

directord/client.py, directord/components/__init__.py, directord/components/builtin_arg.py, directord/components/builtin_copy.py, directord/components/builtin_query.py, directord/components/builtin_run.py, directord/components/builtin_workdir.py, directord/meta.py, directord/server.py, directord/tests/__init__.py, directord/tests/test_components.py, directord/tests/test_utils.py, directord/utils.py, docs/orchestrations.md
The processing bit was being sent multiple times this corrects that
issue.
=> Ensure we're only transmitting the processing bit once

tools/dev-setup.sh
=> remove venv cleanup dir

directord/main.py
=> add verb to job list

.github/workflows/pull-request.yml, components/query_wait.py, directord/client.py, directord/components/builtin_query.py, directord/mixin.py, directord/server.py, docs/components.md, orchestrations/functional-tests-query.yaml
This change adds a query test function to the workflows and provides a
new component to validate the query cache is populated with a correct
value before attempting to use it.
=> Add query test

directord/client.py, directord/components/builtin_query.py, directord/tests/test_client.py
=> simplify client cache opening

directord/components/builtin_cacheevict.py
=> add tag normalization when clearing all cache

directord/__init__.py, directord/client.py, directord/drivers/zmq.py, directord/main.py, directord/mixin.py, directord/server.py, directord/tests/__init__.py, directord/tests/test_drivers_zmq.py, directord/tests/test_main.py, directord/tests/test_server.py, directord/user.py, tests/comparison-orchestration-async.yaml, tools/dev-setup.sh
This change modifies the client so that it's generally more efficient.
An option has been added allowing orchestrations executed via the CLI or the library can be forced to run asynchronously.
=> Ensures that the client side operations are more efficient

directord/__init__.py, directord/client.py, directord/main.py, directord/server.py, directord/tests/test_init.py, directord/tests/test_server.py, directord/tests/test_user.py, directord/user.py
updates to improve the UX when polling, listing, execution jobs.
=> Quality of life improvements

directord/main.py, directord/user.py
=> add more robust poller logic

directord/components/__init__.py, directord/tests/test_components.py
this warning is alraming when there's nothing actually wrong.
=> change warning log to debug

directord/components/builtin_cachefile.py
=> add extend when running cachefile

directord/components/builtin_service.py, directord/tests/test_components.py, docs/components.md
Create a basic component to do systemd service state management.
=> Create systemd service builtin component

directord/server.py, directord/templates/site-index.html, directord/tests/test_mixin.py, directord/tests/test_server.py, directord/utils.py, orchestrations/directord-key-rotation.yaml
=> add more accurate time data

.github/workflows/pull-request.yml, directord/__init__.py, directord/client.py, directord/server.py
Dramatically improve the server processing and client throughput speed when running long operations.
=> faster server processing

directord/components/builtin_workdir.py
=> add info when processing workdir

directord/client.py, directord/tests/test_client.py
=> move component lock to a global

components/query_wait.py, directord/components/builtin_query.py, docs/installation.md, tools/directord-dev-update-catalog.yaml
=> add catalog to assist in patching development clients

components/query_wait.py
=> Update query wait to account for null args

.github/workflows/pull-request.yml, directord/client.py, directord/components/__init__.py, directord/components/builtin_queuesentinel.py, directord/tests/test_components.py, docs/components.md, orchestrations/functional-tests-queue-sentinel.yaml
This new component will allow operators to instruct clients to halt all
further operations.
Fixes: https://github.com/cloudnull/directord/issues/167
=> Add a queue sentinel component

directord/client.py, directord/components/builtin_service.py, orchestrations/directord-key-rotation.yaml, orchestrations/ghost-blog.yaml, orchestrations/openstack-keystone.yaml, orchestrations/podman.yaml, orchestrations/sonarr-radarr-nzbget.yml
=> use service component when restarting services

.github/workflows/pull-request.yml, directord/client.py, directord/server.py
=> Correct target handling when running through the library

directord/client.py, directord/server.py
=> add thread and interval check

.github/workflows/pull-request.yml
=> Add more realistic / stressful functional test

components/container_config_data.py, components/pod.py, directord/__init__.py, directord/client.py, directord/components/builtin_copy.py, directord/drivers/zmq.py, directord/server.py, directord/tests/test_server.py, directord/user.py, orchestrations/functional-tests-async-transfer.yaml
=> add bypass manager set

.github/workflows/pull-request.yml, directord/__init__.py, directord/client.py, directord/components/builtin_copy.py, directord/drivers/__init__.py, directord/drivers/zmq.py, directord/server.py, directord/tests/test_client.py, orchestrations/functional-tests-async-transfer.yaml
Functional tests have been added to ensure we're not breaking out ADD component and that we're running into dead lock issues when running heavy workloads.
Both the Server and Client processes will spawn new worker threads when required. This is done for more efficient resource management across the board.
=> Add functional testing and improve process management

components/query_wait.py, directord/components/builtin_query.py
=> Add identity checks for query wait

components/job_wait.py, directord/components/builtin_query.py, directord/server.py
=> Fix coordination issues

directord/client.py
This is causing issues with query wait not waiting sufficiently enough.
This reverts commit 3f5da260bc83967081b6df36f5bb055fe5ea20c4.
=> Revert "Improve client processor"

directord/components/builtin_query.py, directord/server.py
=> add identity list to QUERY callback

components/job_wait.py, components/query_wait.py, directord/client.py, directord/server.py
=> Improve job wait and target coordination

README.md, directord/server.py
=> fix minor issues with documentation

directord/client.py
=> add dynamic command based locking

directord/client.py
Component locks will now be efficiently cleaned up after use using the
class attributes instead of an array. This is done to ensure we're
always able to cleanup the component locks even if the thread executor
were to crash for a given run.
=> ensure efficient cleanup of dynamic locks

directord/client.py, directord/drivers/__init__.py, directord/drivers/messaging.py, directord/drivers/zmq.py, directord/interface.py, directord/server.py, directord/tests/__init__.py, directord/tests/test_client.py, directord/tests/test_drivers_messaging.py, directord/tests/test_server.py, setup.py
- Add interface to driver class
- Add oslo-messaging driver stub
- Add run method to driver and implement for oslo-messaging
- Abstract heartbeat and add support to oslo-messaging
=> Add support for oslo-messaging as a driver

directord/meta.py
=> rev 0.10.1

components/job_wait.py, components/query_wait.py, components/reboot.py, contrib/container-build/directord.spec, directord/client.py, directord/components/__init__.py, directord/components/builtin_arg.py, directord/components/builtin_copy.py, directord/components/builtin_run.py, directord/datastores/disc.py, directord/drivers/__init__.py, directord/drivers/messaging.py, directord/drivers/zmq.py, directord/interface.py, directord/main.py, directord/server.py, directord/tests/test_client.py, directord/tests/test_components.py, directord/tests/test_drivers_messaging.py, directord/tests/test_drivers_zmq.py, directord/tests/test_server.py, directord/tests/test_utils.py, directord/user.py, directord/utils.py
This change updates the messaging abstractions so that they more completely remove the the ZMQ assumptions in the server and client.
=> Update the messaging abstractions

directord/tests/test_user.py, directord/user.py
=> Degrated -> Degraded

components/job_wait.py, directord/client.py, directord/components/__init__.py, directord/components/builtin_copy.py, directord/drivers/__init__.py, directord/drivers/zmq.py, directord/meta.py, directord/mixin.py, directord/server.py, directord/tests/__init__.py, directord/tests/test_client.py, directord/tests/test_drivers_zmq.py, directord/tests/test_server.py, directord/user.py, directord/utils.py
this change removes more of the zmq specific calls from the core dirctord code base.
The driver api has been cleaned up to show only what is required to be public.
binary encoded control are now string. encoding / decoding has been pushed into the driver.
=> Driver api

directord/client.py, directord/drivers/__init__.py, directord/drivers/messaging.py, directord/drivers/zmq.py, directord/interface.py, directord/meta.py, directord/server.py, directord/tests/test_drivers_messaging.py, directord/tests/test_server.py, docs/index.md, docs/messaging.md
=> add starting documentation for messaging and tweak the driver

directord/client.py, directord/drivers/__init__.py, directord/drivers/messaging.py, directord/server.py, directord/tests/test_client.py, directord/tests/test_server.py
- Run RPC server thread in run_* loop
- Add job handling support for messaging driver
=> Messaging thread cleanup and job support

.github/workflows/pull-request.yml, directord/drivers/messaging.py, directord/main.py, directord/server.py, directord/tests/test_drivers_messaging.py, directord/tests/test_main.py, tools/dev-setup.sh, tools/prod-setup.sh
The messaging driver was bypassing the server and client process thread.
This change updates the messaging driver to ensure that the server and
client processing work within the driver abstract, which will ensure
that the rest of the application functions as expected.
To ensure the backend isn't running at 100%, the backend methods have
also been implemented.
fixes #235
=> fix bug 235

tools/directord-dev-bootstrap-messaging-catalog.yaml
=> add bootstrap catalog for the messaging driver

docs/overview.md
=> add setup section

docs/analysis.md
This change adds the messaging driver results to our matrix.
=> Add message driver analysis

.github/workflows/pull-request.yml, README.md, directord/datastores/redis.py, directord/main.py, directord/server.py, docs/index.md, docs/overview.md
This change updates the datastores to fix an issue with redis which was
the result of all the encoding changes.
New jobs have been added to ensure we're exercising our datastore
options accordingly.
=> update data-store options and documentation

.github/workflows/pull-request.yml, assets/entrypoint, directord/bootstrap.py, directord/drivers/__init__.py, directord/drivers/messaging.py, directord/drivers/zmq.py, directord/interface.py, directord/main.py, directord/tests/__init__.py, directord/tests/test_drivers_messaging.py, directord/tests/test_drivers_zmq.py, directord/tests/test_interface.py, directord/tests/test_main.py, docs/containerization.md, docs/drivers.md, docs/testing.md, pods/pod-directord-test-pod.yaml, tools/ansible-bootstrap-playbook.yaml, tools/config/messaging/qdrouterd.conf, tools/dev-setup.sh, tools/directord-dev-bootstrap-messaging-catalog.yaml, tools/directord-dev-bootstrap-zmq-encryption-catalog.yaml, tools/directord-dev-bootstrap-zmq.yaml, tools/directord-prod-bootstrap-catalog.yaml, tools/scripts/messaging/getcert.sh, tools/scripts/messaging/messaging-ssl-setup.sh, tools/scripts/messaging/set-ca.sh
- Honor env vars in dev-setup.sh
- Add directord_bootstrap magic var for server bootstrap
- Fix bind address in messaging driver
- Fix messaging bootstrap for multiple nodes
=> Fix messaging bootstrap for multiple nodes

directord/components/builtin_wait.py, directord/datastores/disc.py, directord/interface.py, directord/server.py, directord/tests/test_server.py, orchestrations/scale-test-setup.yaml
=> Add several small changes to tune scale testing

directord/server.py
=> remove extra print

.github/workflows/pull-request-podman.yml, orchestrations/functional-podman-test.yaml
Run functional tests for Podman related code in CI.
=> Run full functional tests for CONTAINER_IMAGE component

.github/workflows/pull-request-container.yml, .github/workflows/pull-request-functional.yml, .github/workflows/pull-request-podman.yml, .github/workflows/pull-request-syntax.yml, directord/server.py
Node pruning was being too far delayed, which can cause usability issues
should a node fail. This change ensures the pruning happens in a timely
fashion.
=> fix node pruning

directord/client.py, directord/drivers/__init__.py, directord/drivers/messaging.py, directord/drivers/zmq.py, directord/main.py, directord/server.py, directord/tests/__init__.py, directord/tests/test_main.py, directord/tests/test_server.py, directord/utils.py, docs/overview.md
This change further cleans up un-used code and adjusts the timings for
best performance.
=> updating timings

directord/client.py
=> add poller to client job results

directord/client.py, directord/datastores/disc.py, directord/main.py, directord/server.py, directord/tests/test_client.py, directord/tests/test_datastore_disc.py, directord/tests/test_user.py, directord/user.py, directord/utils.py
While the DBM implementation was functional, it was very slow, resulting
in prolonged execution times, amounting to minutes added to runs. This
change re-implements our caching solution to use a POSIX compliant
datastore.
=> Update disc store to be POSIX compliant

.github/workflows/pull-request-functional.yml, directord/utils.py
=> add functional test for posix datastore

directord/__init__.py, directord/bootstrap.py
=> add bootstrap to the Directord library implementation

directord/utils.py
=> additional updates for POSIX cache types

.github/workflows/pull-request-functional.yml, directord/bootstrap.py, tests/directord-test-catalog-no-srvr.yaml
When targe doesn't include jobs, don't collect them.
=> Fix issue when no jobs for target

directord/utils.py
The filestore, depending on the file system, may return a differnet
create time than the actual time a file is created. This change
implements a builtin method into the Cache class which will return the
birthtime based on object attributes and fall back to stat when
required. This change will allow the Cache method to be more accurate,
when used as a datastore, and ensure efficiency.
=> update file store

directord/bootstrap.py
=> add exception handling for bootstrap

directord/drivers/messaging.py, directord/drivers/zmq.py, directord/mixin.py
=> add more exception handling

directord/server.py
=> add additional error handling for query call backs

directord/components/builtin_wait.py, tools/directord-prod-bootstrap-zmq.yaml
=> add prod-bootstrap and blueprint to query wait

directord/utils.py
=> add cache read lock

directord/components/builtin_wait.py, docs/syntax.md
Increases retry to 10 and also properly handle url/command handling so
they can be properly blueprinted.
=> Fix wait option handling

directord/components/builtin_wait.py, directord/tests/test_components.py
It is status_code not response_code
=> Fix status code check

directord/components/builtin_wait.py, docs/syntax.md
Since it's supposed to be waiting, it doesn't make sense to not have any
retries.
=> Increase default wait retries

directord/drivers/grpcd.py
Need to make sure the server is only started once between the job and
backend processes (or threads).
=> Fixes for grpcd backend

directord/drivers/generated/msg.proto, directord/drivers/generated/msg_pb2.py, directord/drivers/grpcd.py
Improve back end traceability with request ids.
=> Add request id to grpc requests and responses

.github/workflows/pull-request-functional.yml
=> add grpc gate test

directord/__init__.py, directord/tests/test_init.py
=> bootstrap requires the use of multiprocessing

directord/components/lib/__init__.py
This is why we cant have nice things
=> remove coroutine timeout

directord/drivers/grpcd.py
It's excessively chatty at the moment so let's reduce it to just to the
most important parts for tracking.
=> Reduce the debug logging for grpcd

directord/drivers/grpcd.py
* Enable gzip compression by default
* Increase minimum sleep time when no messages/jobs are available to half a second.
=> Grpc increase wait and enable compression

directord/components/lib/__init__.py
The timeout coroutine has been reimplemented so that it can be use in
legacy python 3 environments, while still supporting modern python
environments. The coroutine implements a user defined timeout without
which is both thread and process compatible.
=> reimplement timeout coroutine

.github/workflows/pull-request-functional.yml, directord/client.py, directord/drivers/__init__.py, directord/drivers/zmq.py, directord/main.py, directord/tests/__init__.py, directord/tests/test_components.py, directord/tests/test_datastore_disc.py, directord/tests/test_main.py, directord/utils.py, docs/overview.md
Reverts directord/directord#335
=> Revert "Add durable queue type option for clients"

contrib/container-build/builder.sh, contrib/container-build/directord.spec, contrib/rpm-build.sh
- Name package directord
- Fix errors in rpm-build.sh
- Fix echo statements log path
=> Packaging updates

directord/client.py
=> fix queue purge

directord/interface.py
=> add trap for driver load errors

directord/utils.py
=> move flushqueue to library

components/container_image.py, components/facter.py, components/job_wait.py, directord/components/builtin_arg.py, directord/components/builtin_cacheevict.py, directord/components/builtin_cachefile.py, directord/components/builtin_copy.py, directord/components/builtin_dnf.py, directord/components/builtin_query.py, directord/components/builtin_run.py, directord/components/builtin_service.py, directord/components/builtin_wait.py, directord/components/builtin_workdir.py
=> remove extra verbose log lines from components

docs/drivers.md
=> Update drivers doc for grpcd

directord/components/builtin_service.py
=> Fix help message for service

directord/components/builtin_dnf.py, directord/tests/test_components.py, docs/syntax.md
Specify packages list for '--exclude'.
=> Add exclude option to DNF component

.github/workflows/pull-request-syntax.yml, directord/tests/test_components.py, directord/tests/test_datastore_redis.py, directord/tests/test_drivers_zmq.py
=> add py36 to the support matrix

contrib/container-build/Containerfile, contrib/container-build/builder.sh, contrib/rpm/directord.spec, tools/build-rpms.sh
- Move spec file into rpm dir
- Package systemd unit files
- Build locally with git ref
- Conditionally create builder user
- Update spec based off of RDO feedback
=> Update spec based off of RDO feedback

directord/server.py, tox.ini
=> Allow directord to run as non-root
